"use client";
import { useMemo } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { CHECKPOINTS, MISSIONS, PROJECTS } from "../../domain/pansofie-content";
import { goBadge, goIcon, goPin } from "../../domain/asset-system";

const NAV=[
  ["domov","Domů","home"],["mise","Mise","mission"],["mapa","Mapa","map"],["projekty","Projekty","projects"],["tymy","Týmy","teams"],["portfolio","Portfolio","portfolio"],["mentor","Mentor","mentor"],["profil","Profil","profile"],["nastaveni","Nastavení","settings"],
];
const badges=[["nature","Příroda"],["helper","Pomoc"],["learner","Učení"],["team","Tým"],["creator","Tvůrce"],["explorer","Průzkumník"]];
const missionMedia=["/assets/brand/go/mission-covers/grow-16x9.webp","/assets/brand/go/mission-covers/help-4x5.webp","/assets/brand/go/mission-covers/create-16x9.webp","/assets/brand/go/mission-covers/explore-16x9.webp"];

function Icon({src,label}){return <Image className="go2-icon" src={src} alt="" aria-hidden="true" title={label} width={44} height={44} sizes="44px"/>}
function Header({title,eyebrow="PANSOFIE GO"}){return <header className="go2-screen-head"><div><small>{eyebrow}</small><h1>{title}</h1></div><button aria-label="Upozornění"><Icon src={goIcon("notifications")}/></button></header>}

function Home(){return <><Header title="Ahoj, Káťo! Svět tě potřebuje."/><section className="go2-feature"><Image src="/assets/brand/go/mission-covers/grow-16x9.webp" alt="Pěstování jako mise" width={560} height={315} sizes="(max-width: 480px) 100vw, 360px" priority/><div><span>DNEŠNÍ MISE · +50 XP</span><h2>Vypěstuj první rostlinu</h2><p>Vyber semena, zasaď je a sleduj, co rostlina opravdu potřebuje.</p><button>Začít</button></div></section><h2 className="go2-section-title">Doporučeno pro tebe</h2><div className="go2-mini-grid">{[["nature","Příroda"],["learner","Učení"],["creator","Kreativita"]].map(([id,label])=><article key={id}><Icon src={goBadge(id)}/><b>{label}</b></article>)}</div><section className="go2-week"><div><small>TÝDENNÍ VÝZVA</small><h2>Týden pro čistší okolí</h2><p>3 z 5 kroků</p></div><div className="go2-progress"><span style={{width:"60%"}}/></div></section></>}

function Missions(){return <><Header title="Mise" eyebrow="VÝZVY A ÚKOLY"/><div className="go2-filter"><button className="is-active">Aktivní</button><button>Splněné</button><button>Vše</button></div><div className="go2-list">{MISSIONS.map((m,i)=><article key={m.id}><Image src={missionMedia[i%missionMedia.length]} alt="" width={220} height={160} sizes="92px"/><div><small>{m.program} · +{m.xp} XP</small><h2>{m.title}</h2><p>{m.detail}</p></div><button aria-label={`Přidat ${m.title}`}>+</button></article>)}</div></>}

function MapScreen(){return <><Header title="Mapa" eyebrow="OBJEVUJ KOLEM SEBE"/><div className="go2-filter"><button className="is-active">Vše</button><button>Příroda</button><button>Lidé</button><button>Akce</button></div><section className="go2-map" role="img" aria-label="Orientační mapa bez přesné polohy dětí">{CHECKPOINTS.map((c,i)=><span key={c[0]} style={{left:`${15+(i%3)*32}%`,top:`${18+Math.floor(i/3)*49}%`}}><Image src={goPin(["mission","project","event","lab","mentor"][i%5])} alt="" width={42} height={42} sizes="42px"/></span>)}</section><article className="go2-map-card"><small>DEMO checkpoint</small><h2>{CHECKPOINTS[0][0]}</h2><p>{CHECKPOINTS[0][1]} · orientační lokalita</p><button>Zobrazit</button></article></>}

function Projects(){return <><Header title="Projekty" eyebrow="PŘIDEJ SE NEBO VYTVOŘ"/><div className="go2-projects">{PROJECTS.slice(0,5).map((p,i)=><article key={p.title}><Image src={missionMedia[(i+1)%missionMedia.length]} alt="" width={560} height={315} sizes="(max-width: 480px) 100vw, 360px"/><div><small>{p.tag}</small><h2>{p.title}</h2><p>{p.description}</p><b>{p.status}</b></div></article>)}</div></>}

function Teams(){return <><Header title="Týmy" eyebrow="SPOLUPRÁCE"/><section className="go2-callout"><Icon src={goIcon("teams")}/><h2>Family Team</h2><p>Rodina může sdílet mise a projekty, ale každý má vlastní soukromý prostor a odpovídající oprávnění.</p><button>Vytvořit tým</button></section><div className="go2-team-list">{["Rodina Novákových","Green Hope Praha · DEMO","Školní tým · DEMO"].map((n,i)=><article key={n}><span>{n[0]}</span><div><h2>{n}</h2><p>{i?"Modelový tým":"3 členové · 2 společné mise"}</p></div><button>→</button></article>)}</div></>}

function Portfolio(){return <><Header title="Moje portfolio" eyebrow="EVIDENCE · REFLEXE · RŮST"/><section className="go2-portfolio-hero"><strong>Level 5</strong><span>850 / 1 000 XP</span><div className="go2-progress"><span style={{width:"85%"}}/></div></section><div className="go2-evidence-grid">{[["camera","Foto"],["upload","Výstup"],["reflection","Reflexe"],["verified","Ověřený krok"]].map(([id,label])=><article key={id}><Icon src={goIcon(id)}/><b>{label}</b></article>)}</div><h2 className="go2-section-title">Mé odznaky</h2><div className="go2-badges">{badges.map(([id,label])=><article key={id}><Icon src={goBadge(id)}/><span>{label}</span></article>)}</div><p className="go2-note">XP a odznaky popisují herní postup a zkušenosti. Nejsou veřejným skóre člověka.</p></>}

function Mentor(){return <><Header title="Mentor" eyebrow="AI / ČLOVĚK PRŮVODCE"/><section className="go2-mentor"><div className="go2-avatar">AI</div><h2>Ahoj Káťo! Co chceš dnes posunout?</h2><p>Průvodce pomáhá hledat další krok. Nenahrazuje rodiče, pedagoga ani odbornou pomoc.</p>{["Chci se něco naučit","Potřebuji radu k projektu","Mám nápad","Chci reflektovat misi"].map(x=><button key={x}>{x}<span>→</span></button>)}<label><span>Napiš otázku…</span><input aria-label="Otázka pro mentora"/></label></section></>}

function Profile(){return <><Header title="Profil" eyebrow="TVOJE CESTA A ÚSPĚCHY"/><section className="go2-profile"><div className="go2-avatar go2-avatar--photo">K</div><h2>Káťa</h2><p>@kacenovakova</p><div><span><strong>5</strong> projektů</span><span><strong>28</strong> odznaků</span><span><strong>120</strong> hodin</span></div></section><section className="go2-callout"><h2>Můj příběh</h2><p>Miluju přírodu, tvorbu a projekty, které mají konkrétní smysl.</p></section></>}

function Settings(){return <><Header title="Nastavení" eyebrow="BEZPEČÍ A PŘIZPŮSOBENÍ"/><div className="go2-settings">{[["profile","Můj účet"],["verified","Soukromí a bezpečí"],["teams","Rodinný režim"],["notifications","Upozornění"],["settings","Vzhled a jazyk"],["mentor","Nápověda"]].map(([id,label])=><button key={label}><Icon src={goIcon(id)}/><span>{label}</span><b>›</b></button>)}</div><section className="go2-safety"><Icon src={goIcon("verified")}/><div><h2>Bezpečné prostředí na prvním místě</h2><p>Žádná přesná poloha dítěte a žádný přímý kontakt dítěte s neznámým dospělým.</p></div></section></>}

export default function GoWorkspace({view="domov"}){const router=useRouter();const valid=NAV.some(([id])=>id===view)?view:"domov";const screen=useMemo(()=>valid,[valid]);const content=screen==="domov"?<Home/>:screen==="mise"?<Missions/>:screen==="mapa"?<MapScreen/>:screen==="projekty"?<Projects/>:screen==="tymy"?<Teams/>:screen==="portfolio"?<Portfolio/>:screen==="mentor"?<Mentor/>:screen==="profil"?<Profile/>:<Settings/>;const navigate=id=>router.push(id==="domov"?"/go":`/go/${id}`);return <div className="go2-stage"><aside className="go2-desktop-note"><b>PANSOFIE GO</b><h2>Akce patří do kapsy.</h2><p>Mobile-first rozhraní pro mise, mapu, projekty, týmy, portfolio a průvodce.</p><nav className="go2-all-nav" aria-label="Všechny obrazovky Pansofie GO">{NAV.map(([id,label])=><button key={id} className={screen===id?"is-active":""} onClick={()=>navigate(id)}>{label}</button>)}</nav><a href="/">← Pansofie</a><a href="/young">Pansofie Young →</a></aside><main className="go2-phone"><div className="go2-status"><span>9:41</span><strong>PANSOFIE GO</strong><span>● ● ●</span></div><div className="go2-content">{content}</div><nav className="go2-dock" aria-label="Pansofie GO navigace">{NAV.map(([id,label,icon])=><button key={id} className={screen===id?"is-active":""} aria-current={screen===id?"page":undefined} onClick={()=>navigate(id)}><Icon src={goIcon(icon)}/><span>{label}</span></button>)}</nav></main></div>}
