import React from "react";
import { useLanguage } from "../state/LanguageContext";

const CONTENT = {
  privacy:["Soukromí","Privacy","Jaké údaje prototyp používá","What data the prototype uses","Tato verze ukládá vaše nabídky, volby a rozpracované mise pouze v úložišti tohoto prohlížeče. Poloha se vyžádá jen po vašem kliknutí a neukládá se. Před veřejným provozem bude nutné doplnit identitu správce, účely, právní tituly, příjemce, doby uchování a práva subjektů údajů.","This version stores your offers, choices and mission progress only in this browser. Location is requested only after your click and is not retained. Before public operation, controller identity, purposes, legal bases, recipients, retention periods and data-subject rights must be completed."],
  terms:["Podmínky používání","Terms of use","Co prototyp nabízí","What this prototype provides","Pansofie nyní slouží jako funkční demonstrační prostředí. Nabídky označené DEMO nejsou skutečnými nabídkami a jejich odeslání nevytváří smlouvu. Před veřejným provozem je nutné doplnit provozovatele, odpovědnost, pravidla transakcí a postup reklamací.","Pansofie currently serves as a functional demonstration environment. Offers marked DEMO are not real offers and submitting an action does not create a contract. Operator identity, liability, transaction rules and complaints process must be completed before public operation."],
  cookies:["Cookies a místní úložiště","Cookies and local storage","Co se ukládá v zařízení","What is stored on the device","Prototyp nepoužívá reklamní profilování. Místní úložiště drží jazyk, velikost písma a vámi vytvořený demonstrační obsah. Tyto údaje můžete smazat vymazáním dat webu v prohlížeči.","The prototype does not use advertising profiling. Local storage keeps language, text size and demonstration content you create. You can remove it by clearing site data in your browser."],
  community:["Pravidla komunity","Community rules","Jednáme bezpečně a s respektem","Act safely and respectfully","Nabízejte jen to, co můžete bezpečně předat. Popisujte stav věcí pravdivě. Netlačte na protislužbu, souhlas ani zveřejnění fotografie. Nenahrávejte osobní údaje druhých. Nebezpečný, diskriminační, podvodný nebo sexualizovaný obsah bude odstraněn; podezření lze oznámit přes Kontakt.","Offer only what can be handed over safely. Describe condition truthfully. Do not pressure anyone for a return, consent or a photograph. Do not upload another person’s data. Unsafe, discriminatory, fraudulent or sexualised content will be removed; concerns can be reported through Contact."],
  accessibility:["Přístupnost","Accessibility","Pansofie má být použitelná pro každého","Pansofie should be usable by everyone","Rozhraní podporuje klávesnici, viditelný fokus, přeskočení na obsah, zvětšení písma a dostatečně popsané ovládací prvky. Pokud narazíte na bariéru, popište stránku, zařízení a problém přes Kontakt; odpověď a náhradní způsob přístupu budou doplněny po určení provozovatele.","The interface supports keyboard use, visible focus, skip-to-content, larger text and labelled controls. If you encounter a barrier, describe the page, device and issue via Contact; response timing and an alternative access route will be completed when the operator is identified."],
  safety:["Bezpečnost a ochrana mladých","Safety and safeguarding","Young je zprostředkované prostředí","Young is a mediated environment","Pansofie Young nesmí zobrazovat přesnou polohu dítěte ani umožnit přímý kontakt dítěte s neznámým dospělým. Účast na místní misi zajišťuje rodič, škola nebo ověřená organizace. Podezřelý kontakt ukončete, nic neposílejte a oznamte jej důvěryhodnému dospělému a přes Kontakt.","Pansofie Young must not show a child’s precise location or enable direct contact with an unknown adult. Local mission participation is arranged by a parent, school or verified organisation. End suspicious contact, send nothing, and report it to a trusted adult and through Contact."],
};

export default function LegalPage({type}){const {isEnglish}=useLanguage();const c=CONTENT[type]||CONTENT.terms;return <article className="editorial-page legal-page"><p className="legal-label">LEGAL CANDIDATE · {isEnglish?"NOT LEGAL ADVICE":"NENÍ PRÁVNÍ RADOU"}</p><h1>{isEnglish?c[1]:c[0]}</h1><p className="page-lead">{isEnglish?"Transparent working text for review before public launch.":"Transparentní pracovní text k revizi před veřejným spuštěním."}</p><section><h2>{isEnglish?c[3]:c[2]}</h2><p>{isEnglish?c[5]:c[4]}</p></section><section><h2>{isEnglish?"Status and contact":"Stav a kontakt"}</h2><p>{isEnglish?"This text is incomplete until the operator and processors are identified. Questions and reports can be sent through the contact form.":"Text není úplný, dokud nebude určena identita provozovatele a zpracovatelů. Dotazy a podněty lze poslat přes kontaktní formulář."}</p><a className="text-link" href="/kontakt">{isEnglish?"Go to contact":"Přejít na kontakt"} →</a></section></article>}
