import React from "react";
import Image from "next/image";
import { ArrowRight, MessageCircle, Play, Rocket, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { DOMAINS, MISSIONS, PROJECTS } from "../domain/pansofie-content";
import { youngDoodle, youngIcon } from "../domain/asset-system";

const topics=[
  ["AI a technologie","Příležitosti, rizika a jak je využít smysluplně.","Technologie","/assets/brand/young/photos/creative-studio-16x9.webp"],
  ["Identita a vztahy","Kdo jsem, kam patřím a jak budovat zdravé vztahy.","Lidé","/assets/brand/young/photos/community-cutout.png"],
  ["Společnost a svět","Co se děje kolem nás a jak to spolu souvisí.","Společnost","/assets/brand/young/photos/hero-rooftop-left-safe-16x9.webp"],
  ["Smysl a budoucnost","Kam směřujeme a jaký svět chceme tvořit.","Seberealizace","/assets/brand/young/photos/explorers-nature-16x9.webp"],
];
const stories=[
  ["Jak AI mění způsob, jak se učíme","Technologie · vzdělávání","/assets/brand/young/photos/creative-studio-16x9.webp"],
  ["Proč jsme pořád online a stejně osamělí?","Psychologie · digitální svět","/assets/brand/young/photos/community-cutout.png"],
  ["Má ještě škola připravit na budoucnost?","Vzdělávání · společnost","/assets/brand/pansofie/illustrations/school-learning.webp"],
];

function YoungNav(){return <header className="y2-nav"><Link className="y2-logo" to="/young"><b>YOUNG</b><span>PANSOFIE</span></Link><nav><Link to="/young">Domů</Link><Link to="/young/objevuj">Témata</Link><Link to="/young/komunita">Komunita</Link><Link to="/young/projekty">Projekty</Link><Link to="/young/jak-to-funguje">O nás</Link></nav><div><Link className="y2-search" to="/young/objevuj" aria-label="Hledat"><Search size={18}/></Link><Link className="y2-join" to="/login">Přidej se <ArrowRight size={15}/></Link></div></header>}

function Doodles(){return <><Image className="y2-doodle y2-doodle--crown" src={youngDoodle("crown")} alt="" width={96} height={96} sizes="96px"/><Image className="y2-doodle y2-doodle--heart" src={youngDoodle("heart")} alt="" width={96} height={96} sizes="96px"/><Image className="y2-doodle y2-doodle--wave" src={youngDoodle("wave")} alt="" width={96} height={96} sizes="96px"/></>}

function YoungHome(){return <>
  <section className="y2-hero"><div className="y2-hero-copy"><p>VÍCE NEŽ ODPOVĚDI. SOUVISLOSTI.</p><h1>Chápej svět<br/>ve <span>větších</span><br/>souvislostech.</h1><p>Pro mladé lidi, kteří se ptají, chtějí rozumět, hledají svůj názor a chtějí měnit svět kolem sebe.</p><div><Link className="y2-primary" to="/young/objevuj">Objevuj obsah <ArrowRight size={16}/></Link><Link className="y2-secondary" to="/login">Přidej se k nám</Link></div><div className="y2-values"><span>👥 Komunita, která dává smysl</span><span>💡 Nové pohledy a inspirace</span><span>🚀 Tvé nápady mají cenu</span><span>♥ Lepší svět je možný</span></div></div><figure><Image src="/assets/brand/young/photos/hero-rooftop-left-safe-16x9.webp" alt="Mladí lidé společně tvoří a diskutují" width={960} height={540} sizes="(max-width: 900px) 100vw, 45vw" priority/><Doodles/></figure></section>
  <section className="y2-section"><header><div><h2>Co tu řešíme?</h2><p>Velké otázky skutečného života.</p></div><Link to="/young/objevuj">Všechna témata <ArrowRight size={15}/></Link></header><div className="y2-topic-grid">{topics.map(([title,text,tag,image])=><Link to="/young/objevuj" key={title}><Image src={image} alt="" width={540} height={304} sizes="(max-width: 900px) 100vw, 25vw"/><span>{tag}</span><h3>{title}</h3><p>{text}</p><b>→</b></Link>)}</div></section>
  <section className="y2-section y2-section--stories"><header><div><h2>Co právě letí?</h2><p>Otázky, které teď stojí za pozornost.</p></div></header><div className="y2-story-grid">{stories.map(([title,tag,image])=><article key={title}><Image src={image} alt="" width={540} height={304} sizes="(max-width: 900px) 100vw, 33vw"/><small>{tag}</small><h3>{title}</h3><p>Nové možnosti, nové výzvy. Co to znamená pro naši generaci?</p><ArrowRight/></article>)}</div></section>
  <section className="y2-engage"><h2>Zapoj se!</h2><p>Více než jen čtení. Tvůj prostor k akci.</p><div><Link to="/young/objevuj">🎮 <b>Kvíz</b><span>Otestuj své znalosti.</span></Link><Link to="/young/komunita">💬 <b>Debata týdne</b><span>Co si o tom myslíš?</span></Link><Link to="/young/objevuj">▶ <b>Mini série</b><span>Krátká videa, velké myšlenky.</span></Link><Link to="/young/projekty">🚀 <b>Zkus projekt</b><span>Máš nápad? Pojď ho realizovat.</span></Link></div></section>
  <section className="y2-community-cta"><Image src="/assets/brand/young/photos/community-cutout.png" alt="Komunita Pansofie Young" width={520} height={520} sizes="(max-width: 900px) 80vw, 30vw"/><div><h2>Přidej se do komunity Young Pansofie.</h2><p>Diskutuj, sdílej nápady, tvoř projekty a potkej lidi, kteří chtějí víc než jen scrollovat.</p><Link to="/login">Přidej se <ArrowRight size={15}/></Link></div><div className="y2-community-icons"><span>👥 Noví přátelé</span><span>💡 Inspirace</span><span>🎯 Skutečné projekty</span><span>🌱 Větší souvislosti</span></div></section>
</>}

function YoungExplore(){return <main className="y2-subpage"><header><p>OBJEVUJ</p><h1>Témata, která stojí za to řešit.</h1><p>Ne podle předmětů. Podle skutečného života a otázek, které se navzájem propojují.</p></header><div className="y2-domain-cloud">{DOMAINS.map((d,i)=><span key={d}>{["🪞","🏃","🧠","💛","🤝","🏠","🌍","🌱","⚙","💰","🛠","🎨","🎭","⚖","🏛","🧭"][i]} {d}</span>)}</div><div className="y2-topic-grid">{topics.map(([title,text,tag,image])=><article key={title}><Image src={image} alt="" width={540} height={304} sizes="(max-width: 900px) 100vw, 25vw"/><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div></main>}

function YoungMissions(){return <main className="y2-subpage"><header><p>MISE</p><h1>Zkus něco doopravdy.</h1><p>Krátké výzvy, které propojují učení s konkrétní akcí. XP je herní postup, ne hodnocení člověka.</p></header><div className="y2-mission-grid">{MISSIONS.map(m=><article key={m.id}><Image src={m.image} alt="" width={540} height={320} sizes="(max-width: 900px) 100vw, 33vw"/><small>{m.program} · +{m.xp} XP</small><h2>{m.title}</h2><p>{m.detail}</p><button>Začít misi <ArrowRight size={14}/></button></article>)}</div></main>}

function YoungProjects(){return <main className="y2-subpage"><header><p>PROJEKTY</p><h1>Nápad je začátek. Projekt je krok dál.</h1><p>Přidej se k modelovému projektu nebo si připrav vlastní bezpečný experiment.</p></header><div className="y2-project-grid">{PROJECTS.map((p,i)=><article key={p.title}><Image src={topics[i%topics.length][3]} alt="" width={540} height={304} sizes="(max-width: 900px) 100vw, 33vw"/><span>{p.tag}</span><h2>{p.title}</h2><p>{p.description}</p><small>{p.status}</small></article>)}</div></main>}

function YoungCommunity(){return <main className="y2-subpage"><header><p>KOMUNITA</p><h1>Lidé jako ty. Nápady jako tvoje.</h1><p>Komunitní prostor je navržený kolem témat, týmů a příběhů. U mladších uživatelů bez přímého kontaktu s neznámými dospělými.</p></header><div className="y2-community-board"><article><MessageCircle/><h2>Debata týdne</h2><p>Co by se ve škole mělo učit jinak?</p><button>Přečíst diskusi</button></article><article><Rocket/><h2>Týmové projekty</h2><p>Najdi bezpečný tým kolem tématu, které tě zajímá.</p><button>Projekty</button></article><article><Sparkles/><h2>Příběhy lidí</h2><p>Co někdo zkusil, co se povedlo a co by příště udělal jinak.</p><button>Objevovat</button></article></div></main>}

function YoungHow(){return <main className="y2-subpage"><header><p>JAK TO FUNGUJE</p><h1>Objevuj. Zkoušej. Tvoř. Sdílej. Reflektuj.</h1><p>Young je veřejný obsahový a komunitní web. Akční mise, evidence a portfolio pokračují v Pansofie GO.</p></header><div className="y2-how-grid">{[[youngIcon("explore"),"Objevuj","Ptej se a hledej souvislosti."],[youngIcon("topics"),"Zkoušej","Ověř si nápad v malém."],[youngIcon("projects"),"Tvoř","Proměň otázku v projekt."],[youngIcon("community"),"Spolupracuj","Sdílej bezpečně s ostatními."],[youngIcon("join"),"Měň svět","Udělej konkrétní krok."]].map(([icon,title,text])=><article key={title}><Image src={icon} alt="" width={64} height={64} sizes="64px"/><h2>{title}</h2><p>{text}</p></article>)}</div><aside className="y2-safety"><ShieldCheck/><div><h2>Bezpečnost není skrytá v nastavení.</h2><p>Věk, role, soukromí a pravidla komunikace mění, co je komu dostupné. Přesná poloha dítěte se nepoužívá.</p></div></aside></main>}

export default function YoungPublicPage({ view="home" }){return <div className="y2-world"><YoungNav/>{view==="home"?<YoungHome/>:view==="objevuj"?<YoungExplore/>:view==="mise"?<YoungMissions/>:view==="projekty"?<YoungProjects/>:view==="komunita"?<YoungCommunity/>:<YoungHow/>}<footer className="y2-footer"><div><b>YOUNG PANSOFIE</b><span>Zvídavé myšlení pro smysluplnější svět.</span></div><nav><Link to="/o-nas">Pansofie</Link><Link to="/blog">Blog</Link><Link to="/pro-skoly">Pro školy</Link><Link to="/kontakt">Kontakt</Link></nav></footer></div>}
