import Link from "next/link";

const FAMILY=[["01","Jak to funguje","/jak-to-funguje"],["02","Vize","/vize"],["03","Pro koho","/pro-koho"],["04","Knihovna","/knihovna"]];
export function OrientationFamilyNav({active}){return <nav className="or02-family" aria-label="Orientace v Pansofii">{FAMILY.map(([n,label,href])=><Link className={active===href?"is-active":""} href={href} key={href}><span>{n}</span><strong>{label}</strong></Link>)}</nav>}

function HowField(){const items=[["Rozhlédnout se","najít vstup"],["Vyzkoušet","udělat krok"],["Vytvořit","dát zkušenosti tvar"],["Sdílet","jen když to dává smysl"],["Reflektovat","pochopit, co se změnilo"]];return <div className="or02-how-field"><header><span>JAK TO FUNGUJE</span><strong>Od orientace<br/>ke zkušenosti.</strong></header><ol>{items.map(([t,x],i)=><li key={t}><span>{String(i+1).padStart(2,"0")}</span><strong>{t}</strong><small>{x}</small></li>)}</ol><p>Příležitost, ne povinnost.</p></div>}
function VisionField(){const items=[["Pansofia","Poznávat svět v souvislostech."],["Pampaedia","Růst a učit se celý život."],["Panorthosia","Zlepšovat svět kolem sebe."]];return <div className="or02-vision-field"><header><span>VIZE PANSOFIE</span><strong>Poznat.<br/>Růst.<br/>Zlepšovat.</strong></header><div>{items.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{x}</p></article>)}</div><small>Tři staré pilíře přeložené do současného života.</small></div>}
function WhoField(){const items=[["Mladí","vlastní Young zkušenost"],["Rodiny","společná práce, vlastní identity"],["Školy","řízený učební kontext"],["Organizace","zdroje kolem konkrétní potřeby"],["Komunity","místo, vztah a projekt"]];return <div className="or02-who-field"><header><span>PRO KOHO</span><strong>Různé vstupy.<br/>Jedno jádro.</strong></header><ol>{items.map(([t,x],i)=><li key={t}><span>{String(i+1).padStart(2,"0")}</span><strong>{t}</strong><small>{x}</small></li>)}</ol><p>Kontext mění zkušenost, ne hodnotu člověka.</p></div>}
function LibraryField(){const items=[["Otázka","co chceme pochopit"],["Návod","co lze vyzkoušet"],["Příklad","co se stalo v kontextu"],["Reflexe","co jsme se dozvěděli"],["Zdroj","o co se tvrzení opírá"]];return <div className="or02-library-field"><header><span>KNIHOVNA PANSOFIE</span><strong>Znalost,<br/>která cestuje.</strong></header><div>{items.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{x}</p></article>)}</div><small>Dokud materiál není skutečně publikovaný, není z něj „hotový zdroj“.</small></div>}
export function OrientationHero({variant,kicker,title,lead,primary,secondary}){return <section className={`or02-hero or02-hero--${variant}`} aria-labelledby={`or02-${variant}-title`}><div className="or02-hero__copy"><p className="or02-kicker">{kicker}</p><h1 id={`or02-${variant}-title`}>{title}</h1><p className="or02-hero__lead">{lead}</p><div className="or02-hero__actions">{primary&&<Link className="pw-button pw-button--dark" href={primary.href}>{primary.label}</Link>}{secondary&&<Link className="or02-text-link" href={secondary.href}>{secondary.label} <span aria-hidden="true">↗</span></Link>}</div></div><div className="or02-hero__visual">{variant==="how"&&<HowField/>}{variant==="vision"&&<VisionField/>}{variant==="who"&&<WhoField/>}{variant==="library"&&<LibraryField/>}</div></section>}
export function OrientationStatement({kicker,title,text,aside}){return <section className="or02-statement"><div><p className="or02-kicker">{kicker}</p><h2>{title}</h2></div><div><p>{text}</p>{aside&&<blockquote>{aside}</blockquote>}</div></section>}
export function OrientationPrinciples({items}){return <section className="or02-principles">{items.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</section>}
export function OrientationLedger({items}){return <section className="or02-ledger">{items.map((item,i)=><Link href={item.href} key={item.title}><span>{String(i+1).padStart(2,"0")} · {item.label}</span><h3>{item.title}</h3><p>{item.text}</p>{item.meta&&<small>{item.meta}</small>}<b aria-hidden="true">↗</b></Link>)}</section>}
export function OrientationSequence({title,copy,items}){return <section className="or02-sequence"><header><div><p className="or02-kicker">UČEBNÍ CYKLUS</p><h2>{title}</h2></div><p>{copy}</p></header><ol>{items.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,"0")}</span><strong>{item}</strong></li>)}</ol></section>}
export function OrientationTruth({children}){return <section className="or02-truth"><p className="or02-kicker">PRAVDIVOST</p><p>{children}</p></section>}
export function OrientationNext({kicker="DALŠÍ KROK",title,text,href,label}){return <section className="or02-next"><div><p className="or02-kicker">{kicker}</p><h2>{title}</h2><p>{text}</p></div><Link className="pw-button pw-button--dark" href={href}>{label}</Link></section>}
