import Link from "next/link";

const FAMILY=[["01","Family Team","/family-team"],["02","Knowledge Exchange","/osobni-rust"],["03","Mapa","/mapa"],["04","Mapa koloběhu","/mapa-kolobehu"]];
export function PeoplePlaceFamilyNav({active}){return <nav className="pp02-family" aria-label="Lidé, zkušenost a místa">{FAMILY.map(([n,label,href])=><Link className={active===href?"is-active":""} href={href} key={href}><span>{n}</span><strong>{label}</strong></Link>)}</nav>}

function FamilyField(){const roles=[["Záměr","co chceme společně"],["Role","kdo co právě drží"],["Krok","co skutečně uděláme"],["Reflexe","co si odnášíme"]];return <div className="pp02-family-field"><header><span>RODINA JAKO PRVNÍ TÝM</span><strong>Společně.<br/>Ne jedním účtem.</strong></header><div>{roles.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{x}</p></article>)}</div><small>Každý člen zůstává samostatnou identitou.</small></div>}
function ExchangeField(){return <div className="pp02-exchange-field"><header><span>ZNALOST MEZI GENERACEMI</span><strong>Zkušenost<br/>může cestovat.</strong></header><div className="pp02-exchange-field__pair"><section><span>UMÍM</span><strong>dovednost<br/>příběh<br/>zkušenost</strong></section><i aria-hidden="true">↔</i><section><span>CHCI POZNAT</span><strong>otázku<br/>postup<br/>souvislost</strong></section></div><p>Kontext vytváří bezpečné propojení.</p></div>}
function MapField({checkpoints=[]}){return <div className="pp02-map-field"><header><span>MÍSTO, NE POLOHA ČLOVĚKA</span><strong>Veřejná místa.<br/>Bez sledování lidí.</strong></header><div className="pp02-map-field__plot">{checkpoints.slice(0,6).map(([title,place,type],i)=><div className={`pp02-map-node pp02-map-node--${i+1}`} key={title}><span>{String(i+1).padStart(2,"0")} · {type}</span><strong>{title}</strong><small>{place}</small></div>)}</div><small>DEMO data · orientační model checkpointů</small></div>}
function CycleField(){const flow=[["Zdroj","co je k dispozici"],["Potřeba","co dává smysl řešit"],["Propojení","kde vzniká vztah"],["Další použití","kam hodnota pokračuje"]];return <div className="pp02-cycle-field"><header><span>MAPA KOLOBĚHU</span><strong>Hodnota<br/>nekončí prvním použitím.</strong></header><ol>{flow.map(([t,x],i)=><li key={t}><span>{String(i+1).padStart(2,"0")}</span><strong>{t}</strong><small>{x}</small></li>)}</ol><p>Veřejný web ukazuje princip, ne živé rezervace.</p></div>}

export function PeoplePlaceHero({variant,kicker,title,lead,primary,secondary,checkpoints=[]}){return <section className={`pp02-hero pp02-hero--${variant}`} aria-labelledby={`pp02-${variant}-title`}><div className="pp02-hero__copy"><p className="pp02-kicker">{kicker}</p><h1 id={`pp02-${variant}-title`}>{title}</h1><p className="pp02-hero__lead">{lead}</p><div className="pp02-hero__actions">{primary&&<Link className="pw-button pw-button--dark" href={primary.href}>{primary.label}</Link>}{secondary&&<Link className="pp02-text-link" href={secondary.href}>{secondary.label} <span aria-hidden="true">↗</span></Link>}</div></div><div className="pp02-hero__visual">{variant==="family"&&<FamilyField/>}{variant==="exchange"&&<ExchangeField/>}{variant==="map"&&<MapField checkpoints={checkpoints}/>} {variant==="cycle"&&<CycleField/>}</div></section>}
export function PeoplePlaceStatement({kicker,title,text,aside}){return <section className="pp02-statement"><div><p className="pp02-kicker">{kicker}</p><h2>{title}</h2></div><div><p>{text}</p>{aside&&<blockquote>{aside}</blockquote>}</div></section>}
export function PeoplePlaceLedger({items,className=""}){return <section className={`pp02-ledger ${className}`}>{items.map((item,i)=><article key={item.title}><span>{String(i+1).padStart(2,"0")} · {item.label||"VRSTVA"}</span><h3>{item.title}</h3><p>{item.text}</p>{item.meta&&<small>{item.meta}</small>}</article>)}</section>}
export function PeoplePlaceSequence({title,items}){return <section className="pp02-sequence"><header><p className="pp02-kicker">JAK TO PROBÍHÁ</p><h2>{title}</h2></header><ol>{items.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,"0")}</span><strong>{item}</strong></li>)}</ol></section>}
export function PeoplePlaceTruth({children}){return <section className="pp02-truth"><p className="pp02-kicker">PRAVDIVOST A SOUKROMÍ</p><p>{children}</p></section>}
export function PeoplePlaceNext({kicker="DALŠÍ KROK",title,text,href,label}){return <section className="pp02-next"><div><p className="pp02-kicker">{kicker}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div><Link className="pw-button pw-button--dark" href={href}>{label}</Link></section>}
