import Link from "next/link";

const FAMILY=[["01","Dobrovolnictví","/dobrovolnictvi"],["02","Partnerství","/partnerstvi"],["03","Kontakt","/kontakt"]];
export function EngageFamilyNav({active}){return <nav className="en02-family" aria-label="Zapoj se do Pansofie">{FAMILY.map(([n,label,href])=><Link className={active===href?"is-active":""} href={href} key={href}><span>{n}</span><strong>{label}</strong></Link>)}</nav>}

function VolunteerField(){const items=[["Zájem","co dává smysl"],["Malý krok","co lze opravdu udělat"],["Zkušenost","co si člověk odnese"],["Navázání","kam lze pokračovat"]];return <div className="en02-volunteer-field" aria-label="Dobrovolnictví bez povinného skórování"><header><span>DOBROVOLNICTVÍ</span><strong>Příležitost,<br/>ne povinnost.</strong></header><ol>{items.map(([t,x],i)=><li key={t}><span>{String(i+1).padStart(2,"0")}</span><strong>{t}</strong><small>{x}</small></li>)}</ol><p>Účast není odměňovaná veřejným pořadím lidí.</p></div>}
function PartnershipField(){const items=[["Účel","co řešíme"],["Role","kdo co přináší"],["Rozsah","kde spolupráce platí"],["Důkaz","co lze skutečně doložit"],["Bezpečí","koho a jak chráníme"]];return <div className="en02-partnership-field" aria-label="Partnerství jako dohoda o konkrétní práci"><header><span>PARTNERSTVÍ</span><strong>Dohoda o<br/>konkrétní práci.</strong></header><div>{items.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{x}</p></article>)}</div><small>Logo není výsledek. Vztah musí mít účel, rozsah a odpovědnost.</small></div>}
function ContactField(){const rows=[["Dotaz","co potřebujete"],["Kontext","škola · organizace · komunita · podnět"],["Směr","kam zpráva patří"],["Další krok","co může následovat"]];return <div className="en02-contact-field" aria-label="Kontakt začíná kontextem"><header><span>KONTAKT</span><strong>Kontext dřív<br/>než formulář.</strong></header><ol>{rows.map(([t,x],i)=><li key={t}><span>{String(i+1).padStart(2,"0")}</span><strong>{t}</strong><small>{x}</small></li>)}</ol><p>Současný formulář je lokální prototyp a nic nepředstírá.</p></div>}
export function EngageHero({variant,kicker,title,lead,primary,secondary}){return <section className={`en02-hero en02-hero--${variant}`} aria-labelledby={`en02-${variant}-title`}><div className="en02-hero__copy"><p className="en02-kicker">{kicker}</p><h1 id={`en02-${variant}-title`}>{title}</h1><p className="en02-hero__lead">{lead}</p><div className="en02-hero__actions">{primary&&<Link className="pw-button pw-button--dark" href={primary.href}>{primary.label}</Link>}{secondary&&<Link className="en02-text-link" href={secondary.href}>{secondary.label} <span aria-hidden="true">↗</span></Link>}</div></div><div className="en02-hero__visual">{variant==="volunteer"&&<VolunteerField/>}{variant==="partnership"&&<PartnershipField/>}{variant==="contact"&&<ContactField/>}</div></section>}
export function EngageStatement({kicker,title,text,aside}){return <section className="en02-statement"><div><p className="en02-kicker">{kicker}</p><h2>{title}</h2></div><div><p>{text}</p>{aside&&<blockquote>{aside}</blockquote>}</div></section>}
export function EngagePrinciples({items}){return <section className="en02-principles">{items.map(([t,x],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{x}</p></article>)}</section>}
export function EngageLedger({items}){return <section className="en02-ledger">{items.map((item,i)=><Link href={item.href} key={item.title}><span>{String(i+1).padStart(2,"0")} · {item.label}</span><h3>{item.title}</h3><p>{item.text}</p><b aria-hidden="true">↗</b></Link>)}</section>}
export function EngageTruth({children}){return <section className="en02-truth"><p className="en02-kicker">PRAVDIVOST</p><p>{children}</p></section>}
export function EngageNext({kicker="DALŠÍ KROK",title,text,href,label}){return <section className="en02-next"><div><p className="en02-kicker">{kicker}</p><h2>{title}</h2><p>{text}</p></div><Link className="pw-button pw-button--dark" href={href}>{label}</Link></section>}
