import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Leaf, Compass, Sparkles, Repeat } from "lucide-react";
import PublicNav from "@/components/pansofie/PublicNav";
import SectionHeading from "@/components/pansofie/SectionHeading";
import { PATHS, PROCESS_STEPS } from "@/lib/pansofieData";

export default function JakFunguje() {
  return (
    <div>
      <PublicNav />
      <section className="pt-32 pb-12 sm:pt-40 sm:pb-16"><div className="container-px max-w-4xl mx-auto text-center"><span className="chip bg-primary/10 text-primary mb-5"><Compass size={14} /> Jak Pansofie funguje</span><h1 className="text-4xl sm:text-5xl font-semibold font-display tracking-tight text-balance leading-tight">Není to obsah ke čtení. Je to systém zkušeností.</h1><p className="mt-5 text-lg text-muted-foreground leading-relaxed text-balance">Pansofie tě nepoučuje. Dává ti mise, které uděláš v realitě, a z každé vznikne doložený rozvoj ve tvém portfoliu.</p></div></section>
      <section className="py-16 border-t border-border/60 bg-card/40"><div className="container-px max-w-5xl mx-auto"><SectionHeading eyebrow="Rozvětvená myšlenka" title="Jedna cesta, sedm větví, nekonečné větvení" center /><div className="mt-12 flex flex-col items-center gap-3"><div className="px-5 py-2.5 rounded-2xl bg-foreground text-background text-sm font-semibold font-heading">Ty — jedna celoživotní cesta</div><div className="w-px h-8 bg-border"/><div className="flex flex-wrap justify-center gap-2 max-w-xl">{PATHS.map((p)=>{const Icon=p.icon;return <span key={p.id} className="chip" style={{backgroundColor:`${p.color}18`,color:p.color}}><Icon size={14} strokeWidth={2.4}/>{p.name}</span>})}</div><div className="w-px h-8 bg-border"/><div className="flex flex-wrap items-center justify-center gap-1.5 text-xs text-muted-foreground">{["oblast","mise","zkušenost","výsledek"].map((s,i)=><React.Fragment key={s}><span className="px-3 py-1.5 rounded-full bg-muted/60 font-medium">{s}</span>{i<3&&<span className="text-muted-foreground/60">→</span>}</React.Fragment>)}</div><div className="w-px h-8 bg-border"/><div className="px-5 py-2.5 rounded-2xl bg-primary/10 text-primary text-sm font-semibold font-heading">propojení s lidmi & projekty</div></div></div></section>
      <section className="py-20 border-t border-border/60"><div className="container-px max-w-4xl mx-auto"><SectionHeading eyebrow="Cyklus rozvoje" title="Šest kroků, které se opakují" subtitle="Každý krok je hmatatelný. Žádné abstraktní body — jen skutečné zkušenosti." center /><div className="mt-12 flex flex-col gap-3">{PROCESS_STEPS.map((step,i)=><div key={step.title} className="card-soft p-5 sm:p-6 flex gap-5 items-start"><span className="text-3xl font-display font-semibold text-primary/30 shrink-0 w-10">{i+1}</span><div><h3 className="text-lg font-semibold font-heading">{step.title}</h3><p className="text-sm text-muted-foreground mt-1">{step.desc}</p><p className="text-sm text-foreground/80 mt-2 leading-relaxed">{step.detail}</p></div></div>)}</div></div></section>
      <section className="py-20 border-t border-border/60 bg-card/40"><div className="container-px max-w-4xl mx-auto"><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[{icon:Sparkles,title:"Doložené zkušenosti",text:"Místo bodů sbíráš skutečné, ověřené zkušenosti — s důkazem a reflexí."},{icon:Repeat,title:"Smyčka rozvoje",text:"Mise → zkušenost → profil → další mise. Růst je spirála, ne přímka."},{icon:Leaf,title:"Hmatatelné výsledky",text:"Každá mise končí výsledkem: výrobkem, akcí, výpočtem, projektovým přínosem."}].map((c)=>{const Icon=c.icon;return <div key={c.title} className="card-soft p-6"><Icon size={22} className="text-primary mb-3"/><h3 className="font-semibold font-heading">{c.title}</h3><p className="text-sm text-muted-foreground mt-1.5 leading-relaxed">{c.text}</p></div>})}</div></div></section>
      <section className="py-20 border-t border-border/60"><div className="container-px max-w-4xl mx-auto text-center"><h2 className="text-3xl sm:text-4xl font-semibold font-display tracking-tight text-balance">Začni svou první misi</h2><p className="mt-4 text-lg text-muted-foreground">Vyber si výzvu, udělej ji v realitě a nech ji růst ve svém portfoliu.</p><Link to="/dashboard" className="mt-8 inline-flex items-center gap-2 px-6 py-3.5 bg-primary text-primary-foreground rounded-2xl font-semibold hover:opacity-90 transition-opacity">Začít svou cestu <ArrowRight size={18}/></Link></div></section>
      <footer className="py-12 border-t border-border/60"><div className="container-px max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4"><div className="flex items-center gap-2 font-heading font-bold"><span className="h-7 w-7 rounded-lg bg-primary text-primary-foreground flex items-center justify-center"><Leaf size={15} strokeWidth={2.4}/></span>Pansofie</div><p className="text-sm text-muted-foreground">Poznej sebe. Tvoř s druhými. Zlepšuj svět.</p></div></footer>
    </div>
  );
}
