import { PublicShell } from "../../components/public/PublicShell";
import { OrientationFamilyNav, OrientationHero, OrientationLedger, OrientationNext, OrientationStatement, OrientationTruth } from "../../components/public/PansofieOrientationFrame";
export const metadata={title:"Pro koho je Pansofie",description:"Různé vstupy do Pansofie pro mladé, rodiny, mentory, školy a organizace."};
const ROLES=[{title:"Děti & mladí",text:"Objevovat svět, učit se prakticky a přidávat se k věcem, které dávají smysl.",meta:"nápady · zkušenosti · projekty",href:"/young",label:"MLADÍ"},{title:"Rodiny & lidé",text:"Sdílet čas, dovednosti a společné projekty bez nutnosti jednoho sdíleného účtu.",meta:"rodina · spolupráce · projekty",href:"/family-team",label:"RODINA"},{title:"Senioři & mentoři",text:"Předávat zkušenost a zároveň zůstávat součástí oboustranného učení.",meta:"zkušenost · čas · příběhy",href:"/osobni-rust",label:"ZKUŠENOST"},{title:"Školy",text:"Propojovat výuku s reálnými projekty, komunitou a mezioborovým učením.",meta:"děti · komunita · projekty",href:"/pro-skoly",label:"ŠKOLA"},{title:"Firmy & organizace",text:"Přinášet know-how, materiál, kapacitu nebo partnerství do konkrétních projektů.",meta:"zdroje · know-how · podpora",href:"/pro-organizace",label:"ORGANIZACE"}];
export default function WhoPage(){return <PublicShell active="/pro-koho">
 <OrientationFamilyNav active="/pro-koho"/>
 <OrientationHero variant="who" kicker="PRO KOHO JE PANSOFIE" title={<>Každý může vstoupit jinak.</>} lead="Není potřeba vědět předem, co přesně chcete dělat. Stačí zvolit pohled, který je vám teď nejbližší, nebo se jen rozhlédnout." primary={{href:"/jak-to-funguje",label:"Jak Pansofie funguje"}} secondary={{href:"/sit",label:"Jak se vstupy propojují"}}/>
 <OrientationStatement kicker="JEDEN EKOSYSTÉM · RŮZNÉ VSTUPY" title="Stejný svět nemusí vypadat stejně pro dítě, rodinu, školu a organizaci." text="Společné zůstávají oblasti, projekty, bezpečné vztahy a cesta od poznání ke zkušenosti. Rozhraní a jazyk se přizpůsobují kontextu." aside="Kontext mění zkušenost, ne hodnotu člověka."/>
 <OrientationLedger items={ROLES}/>
 <OrientationTruth>Young je vlastní věkově přiměřená zkušenost. Školy používají řízený kontext. Organizace vstupují přes roli a potřebu. Žádný z těchto vstupů neurčuje hodnotu člověka.</OrientationTruth>
 <OrientationNext kicker="BEZ TLAKU" title="Je v pořádku jen se dívat." text="Pansofie nemá být další platforma, která po člověku hned něco chce. Procházení obsahu je samo o sobě platný způsob, jak začít." href="/jak-to-funguje" label="Jak Pansofie funguje"/>
 </PublicShell>}
